import type { Product, Category } from '@/lib/types';

export const categories: Category[] = [
  { id: '1', name: 'Women\'s Fashion', slug: 'womens-fashion' },
  { id: '2', name: 'Men\'s Fashion', slug: 'mens-fashion' },
  { id: '3', name: 'Kids & Baby', slug: 'kids-baby' },
  { id: '4', name: 'Home & Living', slug: 'home-living' },
  { id: '5', name: 'Beauty & Health', slug: 'beauty-health' },
  { id: '6', name: 'البخور والعطور السودانية', slug: 'sudanese-perfumes' },
  { id: '7', name: 'الأزياء السودانية', slug: 'sudanese-fashion' },
  { id: '8', name: 'مفروشات سودانية', slug: 'sudanese-bedding' },
];

const baseProducts: Product[] = [
  {
    id: '1',
    name: 'Elegant Floral Print Dress',
    description: 'A beautiful floral print dress perfect for summer occasions. Lightweight and comfortable.',
    price: 299.99,
    imageUrl: '/images/fashion/casual/dress-1.jpg',
    dataAiHint: 'floral dress',
    category: categories[0],
    slug: 'elegant-floral-print-dress',
    popularity: 85,
  },
  {
    id: '2',
    name: 'Casual Striped T-Shirt',
    description: 'Comfortable cotton t-shirt with a classic striped pattern. Ideal for everyday wear.',
    price: 149.50,
    imageUrl: '/images/fashion/casual/mens-1.jpg',
    dataAiHint: 'striped t-shirt',
    category: categories[0],
    slug: 'casual-striped-t-shirt',
    popularity: 92,
  },
  {
    id: '3',
    name: 'Slim Fit Denim Jeans',
    description: 'Modern slim fit jeans made with stretch denim for maximum comfort and style.',
    price: 349.00,
    imageUrl: '/images/fashion/casual/jeans-1.jpg',
    dataAiHint: 'denim jeans',
    category: categories[1],
    slug: 'slim-fit-denim-jeans',
    popularity: 78,
  },
  {
    id: '4',
    name: 'Men\'s Classic Oxford Shirt',
    description: 'A timeless Oxford shirt, perfect for both casual and formal settings. Made from premium cotton.',
    price: 279.00,
    imageUrl: '/images/fashion/casual/shirt-1.jpg',
    dataAiHint: 'oxford shirt',
    category: categories[1],
    slug: 'mens-classic-oxford-shirt',
    popularity: 88,
  },
  {
    id: '5',
    name: 'Adorable Baby Onesie Set',
    description: 'Set of three soft cotton onesies for babies. Cute prints and easy snap closures.',
    price: 199.00,
    imageUrl: '/images/fashion/kids/baby-1.jpg',
    dataAiHint: 'baby onesie',
    category: categories[2],
    slug: 'adorable-baby-onesie-set',
    popularity: 95,
  },
  {
    id: '6',
    name: 'Kids\' Graphic Print Hoodie',
    description: 'Warm and stylish hoodie with a fun graphic print. Perfect for cooler days.',
    price: 220.00,
    imageUrl: '/images/fashion/kids/hoodie-1.jpg',
    dataAiHint: 'kids hoodie',
    category: categories[2],
    slug: 'kids-graphic-print-hoodie',
    popularity: 70,
  },
  {
    id: '7',
    name: 'Cozy Throw Blanket',
    description: 'Soft and plush throw blanket to add warmth and style to your living room or bedroom.',
    price: 180.00,
    imageUrl: '/images/home/decor-1.jpg',
    dataAiHint: 'throw blanket',
    category: categories[3],
    slug: 'cozy-throw-blanket',
    popularity: 82,
  },
  {
    id: '8',
    name: 'Modern Ceramic Vase Set',
    description: 'Set of two minimalist ceramic vases, perfect for contemporary home decor.',
    price: 150.00,
    imageUrl: '/images/home/decor-2.jpg',
    dataAiHint: 'ceramic vase',
    category: categories[3],
    slug: 'modern-ceramic-vase-set',
    popularity: 75,
  },
  {
    id: '9',
    name: 'Organic Rosehip Seed Oil',
    description: 'Pure, cold-pressed rosehip seed oil for face and skin. Rich in antioxidants and vitamins.',
    price: 99.00,
    imageUrl: '/images/beauty/makeup-1.jpg',
    dataAiHint: 'beauty oil',
    category: categories[4],
    slug: 'organic-rosehip-seed-oil',
    popularity: 90,
  },
  {
    id: '10',
    name: 'Matte Lipstick Collection',
    description: 'A collection of 5 vibrant matte lipsticks. Long-lasting and smudge-proof.',
    price: 250.00,
    imageUrl: '/images/beauty/makeup-2.jpg',
    dataAiHint: 'lipstick collection',
    category: categories[4],
    slug: 'matte-lipstick-collection',
    popularity: 86,
  },
  {
    id: '11',
    name: 'High-Waisted Leggings',
    description: 'Comfortable and versatile high-waisted leggings, perfect for workouts or casual wear.',
    price: 179.00,
    imageUrl: '/images/fashion/casual/leggings-1.jpg',
    dataAiHint: 'leggings activewear',
    category: categories[0],
    slug: 'high-waisted-leggings',
    popularity: 93,
  },
  {
    id: '12',
    name: 'Men\'s Leather Wallet',
    description: 'Genuine leather wallet with multiple card slots and a sleek design.',
    price: 210.00,
    imageUrl: '/images/fashion/casual/wallet-1.jpg',
    dataAiHint: 'leather wallet',
    category: categories[1],
    slug: 'mens-leather-wallet',
    popularity: 80,
  },
  {
    id: '13',
    name: 'Summer Straw Hat',
    description: 'Elegant wide-brim straw hat, perfect for beach days and summer outings.',
    price: 129.99,
    imageUrl: '/images/fashion/casual/straw-hat-1.jpg',
    dataAiHint: 'straw hat',
    category: categories[0],
    slug: 'summer-straw-hat',
    popularity: 88,
  },
  {
    id: '14',
    name: 'Men\'s Running Shoes',
    description: 'Lightweight and breathable running shoes with superior cushioning.',
    price: 399.99,
    imageUrl: '/images/fashion/casual/running-shoes-1.jpg',
    dataAiHint: 'running shoes',
    category: categories[1],
    slug: 'mens-running-shoes',
    popularity: 95,
  },
  {
    id: '15',
    name: 'Kids\' Backpack',
    description: 'Colorful and durable backpack perfect for school or travel.',
    price: 159.99,
    imageUrl: '/images/fashion/kids/backpack-1.jpg',
    dataAiHint: 'kids backpack',
    category: categories[2],
    slug: 'kids-backpack',
    popularity: 87,
  },
  {
    id: '16',
    name: 'Scented Candle Set',
    description: 'Set of three luxury scented candles in decorative glass jars.',
    price: 189.99,
    imageUrl: '/images/home/decor-3.jpg',
    dataAiHint: 'scented candles',
    category: categories[3],
    slug: 'scented-candle-set',
    popularity: 85,
  },
  {
    id: '17',
    name: 'Professional Makeup Brush Set',
    description: 'Set of 12 professional makeup brushes with soft synthetic bristles and ergonomic handles.',
    price: 299.99,
    imageUrl: '/images/beauty/makeup-3.jpg',
    dataAiHint: 'makeup brushes',
    category: categories[4],
    slug: 'professional-makeup-brush-set',
    popularity: 89,
  },
  {
    id: '18',
    name: 'Luxury Eyeshadow Palette',
    description: '18 highly pigmented eyeshadow colors in matte and shimmer finishes.',
    price: 449.99,
    imageUrl: '/images/beauty/makeup-4.jpg',
    dataAiHint: 'eyeshadow palette',
    category: categories[4],
    slug: 'luxury-eyeshadow-palette',
    popularity: 92,
  },
  {
    id: '19',
    name: 'Long-lasting Foundation',
    description: 'Full coverage liquid foundation with 24-hour wear and natural finish.',
    price: 279.99,
    imageUrl: '/images/beauty/makeup-5.jpg',
    dataAiHint: 'foundation makeup',
    category: categories[4],
    slug: 'long-lasting-foundation',
    popularity: 88,
  },
  {
    id: '20',
    name: 'Kids\' Denim Overall Set',
    description: 'Adorable denim overall set with striped t-shirt for children.',
    price: 349.99,
    imageUrl: '/images/fashion/kids/denim-set-1.jpg',
    dataAiHint: 'kids overall',
    category: categories[2],
    slug: 'kids-denim-overall-set',
    popularity: 86,
  },
  {
    id: '21',
    name: 'Children\'s Party Dress',
    description: 'Beautiful party dress with tulle skirt and bow detail.',
    price: 399.99,
    imageUrl: '/images/fashion/kids/party-dress-1.jpg',
    dataAiHint: 'kids party dress',
    category: categories[2],
    slug: 'childrens-party-dress',
    popularity: 91,
  },
  {
    id: '22',
    name: 'Boys\' Sports Set',
    description: 'Comfortable two-piece sports set with joggers and zip-up jacket.',
    price: 299.99,
    imageUrl: '/images/fashion/kids/sports-set-1.jpg',
    dataAiHint: 'boys sports set',
    category: categories[2],
    slug: 'boys-sports-set',
    popularity: 85,
  },
  {
    id: '23',
    name: 'Women\'s Elegant Heels',
    description: 'Classic stiletto heels in black leather with pointed toe.',
    price: 499.99,
    imageUrl: '/images/fashion/casual/heels-1.jpg',
    dataAiHint: 'womens heels',
    category: categories[0],
    slug: 'womens-elegant-heels',
    popularity: 90,
  },
  {
    id: '24',
    name: 'Women\'s Casual Sneakers',
    description: 'Comfortable and stylish sneakers perfect for everyday wear.',
    price: 449.99,
    imageUrl: '/images/fashion/casual/sneakers-1.jpg',
    dataAiHint: 'womens sneakers',
    category: categories[0],
    slug: 'womens-casual-sneakers',
    popularity: 93,
  },
  {
    id: '25',
    name: 'Women\'s Summer Sandals',
    description: 'Elegant flat sandals with ankle strap and metallic details.',
    price: 299.99,
    imageUrl: '/images/fashion/casual/sandals-1.jpg',
    dataAiHint: 'womens sandals',
    category: categories[0],
    slug: 'womens-summer-sandals',
    popularity: 87,
  },
  {
    id: '26',
    name: 'Men\'s Leather Oxford Shoes',
    description: 'Classic leather oxford shoes in brown, perfect for formal occasions.',
    price: 599.99,
    imageUrl: '/images/fashion/casual/oxford-shoes-1.jpg',
    dataAiHint: 'mens oxford shoes',
    category: categories[1],
    slug: 'mens-leather-oxford-shoes',
    popularity: 89,
  },
  {
    id: '27',
    name: 'Men\'s Athletic Shoes',
    description: 'High-performance athletic shoes with superior cushioning.',
    price: 549.99,
    imageUrl: '/images/fashion/casual/athletic-shoes-1.jpg',
    dataAiHint: 'mens athletic shoes',
    category: categories[1],
    slug: 'mens-athletic-shoes',
    popularity: 94,
  },
  {
    id: '28',
    name: 'Men\'s Casual Loafers',
    description: 'Comfortable slip-on loafers in suede material.',
    price: 449.99,
    imageUrl: '/images/fashion/casual/loafers-1.jpg',
    dataAiHint: 'mens loafers',
    category: categories[1],
    slug: 'mens-casual-loafers',
    popularity: 86,
  },
  {
    id: '29',
    name: 'Waterproof Mascara',
    description: 'Long-lasting waterproof mascara for voluminous lashes.',
    price: 129.99,
    imageUrl: '/images/beauty/makeup-6.jpg',
    dataAiHint: 'mascara',
    category: categories[4],
    slug: 'waterproof-mascara',
    popularity: 91,
  },
  {
    id: '30',
    name: 'Kids\' Winter Jacket',
    description: 'Warm and cozy winter jacket with hood for children.',
    price: 449.99,
    imageUrl: '/images/fashion/kids/winter-jacket-1.jpg',
    dataAiHint: 'kids winter jacket',
    category: categories[2],
    slug: 'kids-winter-jacket',
    popularity: 88,
  },
  {
    id: '31',
    name: 'SHEIN Floral Maxi Dress',
    description: 'Elegant floral print maxi dress with ruffle details and side split. Perfect for summer occasions.',
    price: 799.99,
    imageUrl: '/images/fashion/casual/maxidress-1.jpg',
    dataAiHint: 'floral maxi dress',
    category: categories[0],
    slug: 'shein-floral-maxi-dress',
    popularity: 95,
  },
  {
    id: '32',
    name: 'SHEIN Crop Top & High Waist Pants Set',
    description: 'Trendy two-piece set featuring a crop top and high-waisted wide-leg pants.',
    price: 649.99,
    imageUrl: '/images/fashion/casual/crop-top-set-1.jpg',
    dataAiHint: 'two piece set',
    category: categories[0],
    slug: 'shein-crop-top-pants-set',
    popularity: 93,
  },
  {
    id: '33',
    name: 'SHEIN Oversized Graphic T-Shirt',
    description: 'Street-style oversized t-shirt with modern graphic print.',
    price: 249.99,
    imageUrl: '/images/fashion/casual/oversized-tshirt-1.jpg',
    dataAiHint: 'graphic tshirt',
    category: categories[1],
    slug: 'shein-oversized-graphic-tshirt',
    popularity: 91,
  },
  {
    id: '34',
    name: 'SHEIN High Waist Ripped Jeans',
    description: 'Trendy high-waisted jeans with distressed details and skinny fit.',
    price: 599.99,
    imageUrl: '/images/fashion/casual/ripped-jeans-1.jpg',
    dataAiHint: 'ripped jeans',
    category: categories[0],
    slug: 'shein-high-waist-ripped-jeans',
    popularity: 94,
  },
  {
    id: '35',
    name: 'SHEIN Puff Sleeve Blouse',
    description: 'Romantic puff sleeve blouse with ruched details and square neckline.',
    price: 399.99,
    imageUrl: '/images/fashion/casual/puff-blouse-1.jpg',
    dataAiHint: 'puff sleeve blouse',
    category: categories[0],
    slug: 'shein-puff-sleeve-blouse',
    popularity: 92,
  },
  {
    id: '36',
    name: 'SHEIN Girls Tulle Dress',
    description: 'Adorable tulle dress for girls with bow detail and layered skirt.',
    price: 449.99,
    imageUrl: '/images/fashion/kids/tulle-dress-1.jpg',
    dataAiHint: 'girls dress',
    category: categories[2],
    slug: 'shein-girls-tulle-dress',
    popularity: 90,
  },
  {
    id: '37',
    name: 'SHEIN Pleated Mini Skirt',
    description: 'High-waisted pleated mini skirt in trendy plaid pattern.',
    price: 299.99,
    imageUrl: '/images/fashion/casual/pleated-skirt-1.jpg',
    dataAiHint: 'pleated skirt',
    category: categories[0],
    slug: 'shein-pleated-mini-skirt',
    popularity: 89,
  },
  {
    id: '38',
    name: 'SHEIN Cargo Pants',
    description: 'Stylish high-waist cargo pants with multiple pockets, perfect for casual wear.',
    price: 549.99,
    imageUrl: '/images/fashion/casual/cargo-pants-1.jpg',
    dataAiHint: 'cargo pants',
    category: categories[0],
    slug: 'shein-cargo-pants',
    popularity: 93,
  },
  {
    id: '39',
    name: 'SHEIN Knit Sweater Vest',
    description: 'Trendy sleeveless knit vest in classic argyle pattern.',
    price: 349.99,
    imageUrl: '/images/fashion/casual/sweater-vest-1.jpg',
    dataAiHint: 'sweater vest',
    category: categories[0],
    slug: 'shein-knit-sweater-vest',
    popularity: 88,
  },
  {
    id: '40',
    name: 'SHEIN Cut Out Bodycon Dress',
    description: 'Elegant bodycon dress with modern cut-out details.',
    price: 459.99,
    imageUrl: '/images/fashion/casual/bodycon-dress-1.jpg',
    dataAiHint: 'bodycon dress',
    category: categories[0],
    slug: 'shein-cut-out-bodycon-dress',
    popularity: 92,
  },
  {
    id: '41',
    name: 'SHEIN Tie Dye Loungewear Set',
    description: 'Comfortable tie-dye print sweatshirt and joggers set.',
    price: 599.99,
    imageUrl: '/images/fashion/casual/loungewear-set-1.jpg',
    dataAiHint: 'loungewear set',
    category: categories[0],
    slug: 'shein-tie-dye-loungewear-set',
    popularity: 91,
  },
  {
    id: '42',
    name: 'SHEIN Sequin Party Dress',
    description: 'Glamorous sequin mini dress perfect for parties and special occasions.',
    price: 899.99,
    imageUrl: '/images/fashion/casual/sequin-dress-1.jpg',
    dataAiHint: 'sequin dress',
    category: categories[0],
    slug: 'shein-sequin-party-dress',
    popularity: 94,
  },
  {
    id: '43',
    name: 'SHEIN Boys Denim Set',
    description: 'Stylish denim jacket and jeans set for boys.',
    price: 699.99,
    imageUrl: '/images/fashion/kids/denim-set-2.jpg',
    dataAiHint: 'boys denim set',
    category: categories[2],
    slug: 'shein-boys-denim-set',
    popularity: 87,
  },
  {
    id: '44',
    name: 'SHEIN Platform Sandals',
    description: 'Trendy platform sandals with ankle strap, perfect for summer.',
    price: 499.99,
    imageUrl: '/images/fashion/casual/sandals-2.jpg',
    dataAiHint: 'platform sandals',
    category: categories[0],
    slug: 'shein-platform-sandals',
    popularity: 90,
  },
  {
    id: '45',
    name: 'SHEIN Quilted Shoulder Bag',
    description: 'Chic quilted shoulder bag with chain strap detail.',
    price: 399.99,
    imageUrl: '/images/fashion/casual/shoulder-bag-1.jpg',
    dataAiHint: 'shoulder bag',
    category: categories[0],
    slug: 'shein-quilted-shoulder-bag',
    popularity: 91,
  }
];

// منتجات العطور والبخور السودانية
const sudaneseProducts: Product[] = [
  {
    id: 'sp1',
    name: 'عطر الياسمين السوداني',
    description: 'عطر نسائي فاخر مستوحى من روائح الياسمين السوداني الأصيل، برائحة زهرية ناعمة تدوم طويلاً.',
    price: 399.99,
    imageUrl: '/images/perfumes/jasmine-1.jpg',
    category: categories[5],
    slug: 'sudanese-jasmine-perfume',
    popularity: 95,
    dataAiHint: 'jasmine perfume',
  },
  {
    id: 'sp2',
    name: 'خلطة العروس السودانية',
    description: 'خلطة عطرية تقليدية للعروس السودانية، تحتوي على مزيج من أفخر أنواع العطور والزيوت الطبيعية.',
    price: 599.99,
    imageUrl: '/images/perfumes/bridal-mix.jpg',
    category: categories[5],
    slug: 'sudanese-bride-mix',
    popularity: 98,
    dataAiHint: 'bridal perfume',
  },
  {
    id: 'sp3',
    name: 'بخور الند الأسود الفاخر',
    description: 'بخور الند الأسود السوداني الأصيل، محضر يدوياً من أجود أنواع العود والمسك.',
    price: 299.99,
    imageUrl: '/images/perfumes/black-oud.jpg',
    category: categories[5],
    slug: 'black-oud-bakhoor',
    popularity: 94,
    dataAiHint: 'black oud',
  },
  {
    id: 'sp4',
    name: 'دخون سوداني تقليدي',
    description: 'دخون سوداني محضر من مكونات طبيعية 100%، يترك رائحة منعشة في الملابس والمنزل.',
    price: 199.99,
    imageUrl: '/images/perfumes/dukhan-1.jpg',
    category: categories[5],
    slug: 'traditional-dukhan',
    popularity: 92,
    dataAiHint: 'dukhan',
  },
  {
    id: 'sp5',
    name: 'طقم الحناء السوداني الكامل',
    description: 'طقم كامل يحتوي على الحناء السودانية الطبيعية مع الزيوت والخلطات العطرية التقليدية.',
    price: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1599744615988-c409b586fec3?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'sudanese-henna-set',
    popularity: 96,
    dataAiHint: 'henna set',
  },
  {
    id: 'sp6',
    name: 'زيت السمسم السوداني العطري',
    description: 'زيت السمسم السوداني المعطر بالأعشاب الطبيعية، مثالي للشعر والبشرة.',
    price: 159.99,
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'aromatic-sesame-oil',
    popularity: 90,
    dataAiHint: 'sesame oil',
  },
  {
    id: 'sp7',
    name: 'مجموعة الدلكة السودانية',
    description: 'خلطة الدلكة السودانية التقليدية للعناية بالبشرة، تحتوي على الكركم والصندل والأعشاب الطبيعية.',
    price: 349.99,
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'dilka-set',
    popularity: 93,
    dataAiHint: 'dilka',
  },
  {
    id: 'sp8',
    name: 'عطر المسك السوداني المركز',
    description: 'عطر المسك السوداني المركز بتركيبة خاصة، رائحة شرقية فاخرة تدوم طويلاً.',
    price: 499.99,
    imageUrl: 'https://images.unsplash.com/photo-1594900077744-57bbd4d95cc3?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'concentrated-musk',
    popularity: 97,
    dataAiHint: 'musk perfume',
  },
  {
    id: 'sp9',
    name: 'مبخرة نحاسية منقوشة',
    description: 'مبخرة نحاسية سودانية تقليدية مع نقوش يدوية جميلة، مثالية للبخور والعود.',
    price: 259.99,
    imageUrl: 'https://images.unsplash.com/photo-1602874801007-aa87920646c4?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'engraved-copper-burner',
    popularity: 89,
    dataAiHint: 'copper burner',
  },
  {
    id: 'sp10',
    name: 'خلطة القرنفل والورد السوداني',
    description: 'خلطة عطرية مميزة من القرنفل والورد السوداني، تمنح رائحة منعشة ودافئة.',
    price: 279.99,
    imageUrl: 'https://images.unsplash.com/photo-1616166330003-8e1b0e1e7bcd?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'clove-rose-mix',
    popularity: 91,
    dataAiHint: 'clove rose',
  },
  {
    id: 'sp11',
    name: 'طقم العروس السوداني الكامل',
    description: 'طقم كامل للعروس يشمل البخور والدلكة والحناء والعطور التقليدية السودانية الفاخرة.',
    price: 1299.99,
    imageUrl: 'https://images.unsplash.com/photo-1583916087030-a5c85c1e0c2c?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'complete-bride-set',
    popularity: 99,
    dataAiHint: 'bridal set',
  },
  {
    id: 'sp12',
    name: 'خلطة الكركم السودانية للبشرة',
    description: 'خلطة طبيعية من الكركم والأعشاب السودانية للعناية بالبشرة وتفتيحها.',
    price: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1612564148954-59545876eaa0?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'turmeric-skin-mix',
    popularity: 94,
    dataAiHint: 'turmeric mix',
  },
  {
    id: 'sp13',
    name: 'زيت الصندل السوداني المركز',
    description: 'زيت الصندل السوداني الأصلي المركز، مثالي للشعر والبشرة وللاستخدام كعطر.',
    price: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'sandalwood-oil',
    popularity: 92,
    dataAiHint: 'sandalwood oil',
  },
  {
    id: 'sp14',
    name: 'مجموعة الطيب السوداني',
    description: 'مجموعة متكاملة من الطيب السوداني الأصلي مع المبخرة والفحم.',
    price: 349.99,
    imageUrl: 'https://images.unsplash.com/photo-1602874801007-aa87920646c4?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'teeb-set',
    popularity: 96,
    dataAiHint: 'teeb set',
  },
  {
    id: 'sp15',
    name: 'خلطة الليمون والمسك',
    description: 'خلطة عطرية فريدة من الليمون السوداني والمسك، تمنح رائحة منعشة ودائمة.',
    price: 279.99,
    imageUrl: 'https://images.unsplash.com/photo-1616166330003-8e1b0e1e7bcd?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'lemon-musk-mix',
    popularity: 90,
    dataAiHint: 'lemon musk',
  },
  {
    id: 'sp16',
    name: 'مجموعة العود السوداني الملكي',
    description: 'مجموعة فاخرة من العود السوداني الملكي مع المبخرة النحاسية المنقوشة.',
    price: 899.99,
    imageUrl: 'https://images.unsplash.com/photo-1575344987100-b20837c67216?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'royal-oud-set',
    popularity: 98,
    dataAiHint: 'royal oud',
  },
  {
    id: 'sp17',
    name: 'خلطة الحلبة السودانية للشعر',
    description: 'خلطة طبيعية من الحلبة والأعشاب السودانية لتقوية وتطويل الشعر.',
    price: 189.99,
    imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'fenugreek-hair-mix',
    popularity: 93,
    dataAiHint: 'hair care',
  },
  {
    id: 'sp18',
    name: 'عطر الورد والياسمين السوداني',
    description: 'مزيج فاخر من الورد والياسمين السوداني، عطر نسائي أنيق ودائم.',
    price: 549.99,
    imageUrl: 'https://images.unsplash.com/photo-1592914610354-fd354ea45e48?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'rose-jasmine-perfume',
    popularity: 95,
    dataAiHint: 'floral perfume',
  },
  {
    id: 'sp19',
    name: 'مجموعة التجميل السودانية التقليدية',
    description: 'مجموعة كاملة من مستحضرات التجميل السودانية التقليدية للعناية بالبشرة.',
    price: 799.99,
    imageUrl: 'https://images.unsplash.com/photo-1596704017452-0f15b4591a4e?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'traditional-beauty-set',
    popularity: 97,
    dataAiHint: 'beauty set',
  },
  {
    id: 'sp20',
    name: 'خلطة العنبر والمسك الملكية',
    description: 'خلطة ملكية فاخرة من العنبر والمسك السوداني، عطر فاخر للمناسبات الخاصة.',
    price: 999.99,
    imageUrl: 'https://images.unsplash.com/photo-1594900077744-57bbd4d95cc3?w=800&auto=format&fit=crop',
    category: categories[5],
    slug: 'royal-amber-musk',
    popularity: 99,
    dataAiHint: 'luxury perfume',
  }
];

// الأزياء السودانية
const sudaneseFashion: Product[] = [
  {
    id: 'sf1',
    name: 'جلابية علي الله سودانية فاخرة',
    description: 'جلابية علي الله سودانية مطرزة يدوياً بتصميم عصري وخامة فاخرة، مناسبة للمناسبات الخاصة.',
    price: 1599.99,
    imageUrl: '/images/fashion/traditional/jalabiya-1.jpg',
    category: categories[6],
    slug: 'luxury-ala-allah-jalabiya',
    popularity: 98,
    dataAiHint: 'traditional dress',
  },
  {
    id: 'sf2',
    name: 'عباية سودانية مطرزة',
    description: 'عباية سودانية أنيقة مع تطريز يدوي راقي، مصنوعة من أجود أنواع الأقمشة.',
    price: 899.99,
    imageUrl: '/images/fashion/casual/abaya-1.jpg',
    category: categories[6],
    slug: 'embroidered-abaya',
    popularity: 95,
    dataAiHint: 'embroidered abaya',
  },
  {
    id: 'sf3',
    name: 'جلابية سودانية كاجوال',
    description: 'جلابية سودانية عصرية للاستخدام اليومي، مريحة وأنيقة مع تطريز بسيط.',
    price: 499.99,
    imageUrl: '/images/fashion/casual/jalabiya-1.jpg',
    category: categories[6],
    slug: 'casual-jalabiya',
    popularity: 92,
    dataAiHint: 'casual dress',
  },
  {
    id: 'sf4',
    name: 'طقم ثوب سوداني تقليدي',
    description: 'طقم ثوب سوداني تقليدي كامل يشمل الثوب والشال المطابق، مناسب للمناسبات.',
    price: 799.99,
    imageUrl: '/images/fashion/bridal/thobe-set-1.jpg',
    category: categories[6],
    slug: 'traditional-thobe-set',
    popularity: 94,
    dataAiHint: 'traditional set',
  },
  {
    id: 'sf5',
    name: 'فستان سوداني عصري',
    description: 'فستان سوداني بتصميم عصري يجمع بين الأصالة والحداثة، مناسب للحفلات.',
    price: 1299.99,
    imageUrl: '/images/fashion/casual/modern-dress-1.jpg',
    category: categories[6],
    slug: 'modern-sudanese-dress',
    popularity: 96,
    dataAiHint: 'modern dress',
  },
  {
    id: 'sf6',
    name: 'طقم ملابس داخلية سودانية',
    description: 'طقم ملابس داخلية سودانية تقليدية مصنوعة من القطن الطبيعي 100%.',
    price: 299.99,
    imageUrl: '/images/fashion/casual/undergarments-1.jpg',
    category: categories[6],
    slug: 'traditional-undergarments',
    popularity: 88,
    dataAiHint: 'undergarments',
  },
  {
    id: 'sf7',
    name: 'جلابية علي الله مطرزة بالذهبي',
    description: 'جلابية علي الله فاخرة مع تطريز ذهبي يدوي، مثالية للمناسبات الخاصة والأعراس.',
    price: 1899.99,
    imageUrl: '/images/fashion/bridal/gold-ala-allah-1.jpg',
    category: categories[6],
    slug: 'gold-embroidered-ala-allah',
    popularity: 97,
    dataAiHint: 'luxury dress',
  },
  {
    id: 'sf8',
    name: 'عباية سودانية مطرزة بالكريستال',
    description: 'عباية سودانية فاخرة مزينة بالكريستال والتطريز اليدوي الراقي.',
    price: 1299.99,
    imageUrl: '/images/fashion/bridal/crystal-abaya-1.jpg',
    category: categories[6],
    slug: 'crystal-abaya',
    popularity: 94,
    dataAiHint: 'luxury abaya',
  },
  {
    id: 'sf9',
    name: 'طقم عروس سوداني تقليدي',
    description: 'طقم عروس سوداني تقليدي كامل يشمل الثوب والإكسسوارات والحلي التقليدية.',
    price: 2999.99,
    imageUrl: '/images/fashion/bridal/bridal-set-1.jpg',
    category: categories[6],
    slug: 'bridal-set',
    popularity: 99,
    dataAiHint: 'bridal wear',
  },
  {
    id: 'sf10',
    name: 'جلابية سودانية للمنزل',
    description: 'جلابية سودانية مريحة للمنزل، مصنوعة من القطن الناعم مع تطريز بسيط.',
    price: 399.99,
    imageUrl: '/images/fashion/casual/home-jalabiya-1.jpg',
    category: categories[6],
    slug: 'home-jalabiya',
    popularity: 90,
    dataAiHint: 'home wear',
  },
  {
    id: 'sf11',
    name: 'طقم ملابس داخلية عصري',
    description: 'طقم ملابس داخلية سودانية بتصميم عصري وخامات مريحة.',
    price: 249.99,
    imageUrl: '/images/fashion/casual/modern-undergarments-1.jpg',
    category: categories[6],
    slug: 'modern-undergarments',
    popularity: 87,
    dataAiHint: 'modern undergarments',
  },
  {
    id: 'sf12',
    name: 'عباية سودانية كاجوال',
    description: 'عباية سودانية عملية للاستخدام اليومي بتصميم بسيط وأنيق.',
    price: 599.99,
    imageUrl: '/images/fashion/casual/casual-abaya-1.jpg',
    category: categories[6],
    slug: 'casual-abaya',
    popularity: 91,
    dataAiHint: 'casual abaya',
  }
];

// مفروشات سودانية
const sudaneseBedding: Product[] = [
  {
    id: 'sb1',
    name: 'طقم ملاية سرير سوداني تقليدي',
    description: 'طقم ملاية سرير سوداني مطرز يدوياً، يشمل ملاية سرير مزدوج مع 4 أكياس مخدات مطرزة.',
    price: 899.99,
    imageUrl: '/images/bedding/traditional/set-1.jpg',
    category: categories[7],
    slug: 'traditional-bedsheet-set',
    popularity: 96,
    dataAiHint: 'bedding set',
  },
  {
    id: 'sb2',
    name: 'ملاية سرير عروس سودانية',
    description: 'ملاية سرير فاخرة للعروس مع تطريز ذهبي وكريستال، تشمل ملاية مزدوجة و6 أكياس مخدات.',
    price: 1499.99,
    imageUrl: '/images/bedding/bridal-set-1.jpg',
    category: categories[7],
    slug: 'bridal-bedsheet-set',
    popularity: 98,
    dataAiHint: 'bridal bedding',
  },
  {
    id: 'sb3',
    name: 'ملاية قطن سوداني مطرزة',
    description: 'ملاية سرير من القطن السوداني 100% مع تطريز تقليدي، مناسبة للسرير المزدوج.',
    price: 599.99,
    imageUrl: '/images/bedding/traditional/cotton-set-1.jpg',
    category: categories[7],
    slug: 'cotton-embroidered-sheet',
    popularity: 94,
    dataAiHint: 'cotton sheet',
  },
  {
    id: 'sb4',
    name: 'طقم ملاية أطفال سوداني',
    description: 'طقم ملاية سرير أطفال مطرز بتصاميم سودانية تقليدية، يشمل ملاية وكيسين مخدة.',
    price: 399.99,
    imageUrl: '/images/bedding/modern/kids-set-1.jpg',
    category: categories[7],
    slug: 'kids-bedsheet-set',
    popularity: 92,
    dataAiHint: 'kids bedding',
  },
  {
    id: 'sb5',
    name: 'ملاية سرير مطرزة بالكريستال',
    description: 'ملاية سرير فاخرة مزينة بالكريستال والخرز، تصميم عصري مع لمسات تقليدية.',
    price: 1299.99,
    imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&auto=format&fit=crop',
    category: categories[7],
    slug: 'crystal-bedsheet',
    popularity: 95,
    dataAiHint: 'luxury bedding',
  },
  {
    id: 'sb6',
    name: 'طقم ملاية سرير يومي',
    description: 'طقم ملاية سرير للاستخدام اليومي، قطن سوداني ناعم مع تطريز بسيط.',
    price: 449.99,
    imageUrl: '/images/bedding/modern/daily-set-1.jpg',
    category: categories[7],
    slug: 'daily-bedsheet-set',
    popularity: 91,
    dataAiHint: 'daily bedding',
  },
  {
    id: 'sb7',
    name: 'ملاية سرير مطرزة بالذهبي',
    description: 'ملاية سرير فاخرة مع تطريز ذهبي يدوي، تصميم كلاسيكي سوداني.',
    price: 999.99,
    imageUrl: '/images/bedding/traditional/gold-sheet-1.jpg',
    category: categories[7],
    slug: 'gold-embroidered-sheet',
    popularity: 97,
    dataAiHint: 'gold bedding',
  },
  {
    id: 'sb8',
    name: 'طقم ملاية سرير عصري',
    description: 'طقم ملاية سرير بتصميم عصري مع لمسات سودانية تقليدية، خامة فاخرة.',
    price: 799.99,
    imageUrl: '/images/bedding/modern/modern-set-1.jpg',
    category: categories[7],
    slug: 'modern-bedsheet-set',
    popularity: 93,
    dataAiHint: 'modern bedding',
  }
];

// تصدير جميع المنتجات
export const products: Product[] = [...baseProducts, ...sudaneseProducts, ...sudaneseFashion, ...sudaneseBedding];
