
import type { Product, Category } from '@/lib/types';

export const categories: Category[] = [
  { id: '1', name: 'Women\'s Fashion', slug: 'womens-fashion' },
  { id: '2', name: 'Men\'s Fashion', slug: 'mens-fashion' },
  { id: '3', name: 'Kids & Baby', slug: 'kids-baby' },
  { id: '4', name: 'Home & Living', slug: 'home-living' },
  { id: '5', name: 'Beauty & Health', slug: 'beauty-health' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Elegant Floral Print Dress',
    description: 'A beautiful floral print dress perfect for summer occasions. Lightweight and comfortable.',
    price: 299.99,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'floral dress',
    category: categories[0],
    slug: 'elegant-floral-print-dress',
    popularity: 85,
  },
  {
    id: '2',
    name: 'Casual Striped T-Shirt',
    description: 'Comfortable cotton t-shirt with a classic striped pattern. Ideal for everyday wear.',
    price: 149.50,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'striped t-shirt',
    category: categories[0],
    slug: 'casual-striped-t-shirt',
    popularity: 92,
  },
  {
    id: '3',
    name: 'Slim Fit Denim Jeans',
    description: 'Modern slim fit jeans made with stretch denim for maximum comfort and style.',
    price: 349.00,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'denim jeans',
    category: categories[1],
    slug: 'slim-fit-denim-jeans',
    popularity: 78,
  },
  {
    id: '4',
    name: 'Men\'s Classic Oxford Shirt',
    description: 'A timeless Oxford shirt, perfect for both casual and formal settings. Made from premium cotton.',
    price: 279.00,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'oxford shirt',
    category: categories[1],
    slug: 'mens-classic-oxford-shirt',
    popularity: 88,
  },
  {
    id: '5',
    name: 'Adorable Baby Onesie Set',
    description: 'Set of three soft cotton onesies for babies. Cute prints and easy snap closures.',
    price: 199.00,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'baby onesie',
    category: categories[2],
    slug: 'adorable-baby-onesie-set',
    popularity: 95,
  },
  {
    id: '6',
    name: 'Kids\' Graphic Print Hoodie',
    description: 'Warm and stylish hoodie with a fun graphic print. Perfect for cooler days.',
    price: 220.00,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'kids hoodie',
    category: categories[2],
    slug: 'kids-graphic-print-hoodie',
    popularity: 70,
  },
  {
    id: '7',
    name: 'Cozy Throw Blanket',
    description: 'Soft and plush throw blanket to add warmth and style to your living room or bedroom.',
    price: 180.00,
    imageUrl: 'https://placehold.co/800x600.png',
    dataAiHint: 'throw blanket',
    category: categories[3],
    slug: 'cozy-throw-blanket',
    popularity: 82,
  },
  {
    id: '8',
    name: 'Modern Ceramic Vase Set',
    description: 'Set of two minimalist ceramic vases, perfect for contemporary home decor.',
    price: 150.00,
    imageUrl: 'https://placehold.co/600x600.png',
    dataAiHint: 'ceramic vase',
    category: categories[3],
    slug: 'modern-ceramic-vase-set',
    popularity: 75,
  },
  {
    id: '9',
    name: 'Organic Rosehip Seed Oil',
    description: 'Pure, cold-pressed rosehip seed oil for face and skin. Rich in antioxidants and vitamins.',
    price: 99.00,
    imageUrl: 'https://placehold.co/400x400.png',
    dataAiHint: 'beauty oil',
    category: categories[4],
    slug: 'organic-rosehip-seed-oil',
    popularity: 90,
  },
  {
    id: '10',
    name: 'Matte Lipstick Collection',
    description: 'A collection of 5 vibrant matte lipsticks. Long-lasting and smudge-proof.',
    price: 250.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lipstick collection',
    category: categories[4],
    slug: 'matte-lipstick-collection',
    popularity: 86,
  },
  {
    id: '11',
    name: 'High-Waisted Leggings',
    description: 'Comfortable and versatile high-waisted leggings, perfect for workouts or casual wear.',
    price: 179.00,
    imageUrl: 'https://placehold.co/600x800.png',
    dataAiHint: 'leggings activewear',
    category: categories[0],
    slug: 'high-waisted-leggings',
    popularity: 93,
  },
  {
    id: '12',
    name: 'Men\'s Leather Wallet',
    description: 'Genuine leather wallet with multiple card slots and a sleek design.',
    price: 210.00,
    imageUrl: 'https://placehold.co/400x300.png',
    dataAiHint: 'leather wallet',
    category: categories[1],
    slug: 'mens-leather-wallet',
    popularity: 80,
  },
];
